# Generated by Django 5.1.2 on 2024-10-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_farsi', models.CharField(max_length=255)),
                ('title_english', models.CharField(max_length=255)),
                ('authenticity', models.CharField(choices=[('org', 'اورجینال')], default='org', max_length=3)),
                ('warranty', models.CharField(choices=[('h', 'دارد'), ('dh', 'ندارد')], default='h', max_length=2)),
                ('shiping_method', models.CharField(choices=[('pi', 'پیشتاز')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='store/product-category-images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='store/product-subcategory-images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='store.productcategory')),
            ],
        ),
    ]
