# Generated by Django 5.1.2 on 2024-11-01 14:35

import django.core.validators
import django.db.models.deletion
import store.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_num', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('shabaa_num', models.CharField(max_length=55)),
                ('mobile_num', models.CharField(max_length=12, validators=[django.core.validators.validate_integer])),
                ('phone_num', models.CharField(max_length=12, validators=[django.core.validators.validate_integer])),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('store_code', models.CharField(default=store.models.generate_store_code, max_length=10, unique=True)),
                ('store_type', models.CharField(choices=[('ha', 'حقیقی'), ('ho', 'حقوقی')], max_length=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.city')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantaghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('image', models.ImageField(upload_to='store/product-category-images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code_color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HaghighyStore',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.store')),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('national_code', models.CharField(max_length=15, validators=[django.core.validators.validate_integer])),
                ('shomaare_shenasnaame', models.CharField(max_length=15, validators=[django.core.validators.validate_integer])),
            ],
            bases=('store.store',),
        ),
        migrations.CreateModel(
            name='HoghoughyStore',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.store')),
                ('name_CEO', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('registration_num', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=255, verbose_name='شناسه (کد) ملی')),
                ('economic_code', models.CharField(max_length=255)),
            ],
            bases=('store.store',),
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_farsi', models.CharField(max_length=255)),
                ('title_english', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('authenticity', models.CharField(choices=[('org', 'اورجینال'), ('hc', 'های کپی'), ('c', 'کپی')], default='org', max_length=3)),
                ('warranty', models.CharField(choices=[('h', 'دارد'), ('dh', 'ندارد')], default='h', max_length=2)),
                ('shiping_method', models.CharField(choices=[('pi', 'پیشتاز'), ('ti', 'تیپاکس'), ('ba', 'باربری'), ('mo', 'پیک موتوری')], max_length=2)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='mantaghe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.mantaghe'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_recipient', models.CharField(max_length=255)),
                ('mobile_recipient', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('email_recipient', models.EmailField(max_length=254)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('pelaak', models.CharField(max_length=15)),
                ('vaahed', models.CharField(max_length=3)),
                ('post_code', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('referrer_code', models.CharField(max_length=255)),
                ('tracking_code', models.CharField(default=store.models.generate_order_tracking_code, max_length=25, unique=True)),
                ('status', models.CharField(choices=[('ou', 'جاری'), ('od', 'تحویل داده شده'), ('or', 'مرجوع شده'), ('oc', 'لغو شده')], default='ou', max_length=2)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.customer')),
                ('mantaghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.mantaghe')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.province')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=4, null=True)),
                ('inventory', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('unit', models.CharField(blank=True, choices=[('p', 'جفت')], max_length=1, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('discount_percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_discount_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_discount_datetime', models.DateTimeField(blank=True, null=True)),
                ('length_package', models.IntegerField(blank=True, null=True)),
                ('width_package', models.IntegerField(blank=True, null=True)),
                ('height_package', models.IntegerField(blank=True, null=True)),
                ('weight_package', models.IntegerField(blank=True, null=True)),
                ('shenaase_kaala', models.CharField(max_length=25)),
                ('barcode', models.CharField(max_length=25)),
                ('product_status', models.CharField(choices=[('ap', 'تایید شده'), ('w', 'در انتظار تایید'), ('na', 'تایید نشده')], default='w', max_length=2)),
                ('active_status', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, help_text='به هنگام  خارج کردن وضعیت محصول از در انتظار تایید این بخش پر شود', null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.baseproduct')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='panel.staff')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.productcolor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.baseproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/product-images/')),
                ('is_cover', models.BooleanField(default=False)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.baseproduct')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='properties',
            field=models.ManyToManyField(related_name='categories', to='store.productproperties'),
        ),
        migrations.CreateModel(
            name='ProductReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.productcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('image', models.ImageField(upload_to='store/product-subcategory-images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='store.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.productsubcategory'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='store.productcategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='store.productsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.producttype'),
        ),
        migrations.AddField(
            model_name='store',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.province'),
        ),
        migrations.CreateModel(
            name='ReportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='store.baseproduct')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productproperties')),
            ],
        ),
        migrations.CreateModel(
            name='ShipingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('shiping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiping_cost', to='store.shipingmethod')),
            ],
        ),
        migrations.CreateModel(
            name='ShipingProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiping_method', models.ManyToManyField(related_name='shiping_method', to='store.shipingmethod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiping_property', to='store.store')),
                ('shiping_range', models.ManyToManyField(related_name='shiping_property', to='store.shipingrange')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products', to='store.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_products', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
