# Generated by Django 5.1.2 on 2024-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='product_code',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
