# Generated by Django 5.1.2 on 2024-11-01 14:38

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=store.models.generate_product_code, max_length=6, unique=True),
        ),
    ]
