# Generated by Django 5.1.2 on 2024-10-12 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_baseproduct_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=4)),
                ('inventory', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('p', 'جفت')], max_length=1)),
                ('unit_price', models.IntegerField()),
                ('discount_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_discount_datetime', models.DateTimeField()),
                ('end_discount_datetime', models.DateTimeField()),
                ('length_package', models.IntegerField()),
                ('width_package', models.IntegerField()),
                ('height_package', models.IntegerField()),
                ('weight_package', models.IntegerField()),
                ('shenaase_kaala', models.CharField(max_length=25)),
                ('barcode', models.CharField(max_length=25)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.baseproduct')),
            ],
        ),
    ]
