# Generated by Django 5.1.2 on 2024-11-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_baseproduct_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.productcategory'),
        ),
    ]
