# Generated by Django 5.1.2 on 2024-10-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('shiping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiping_cost', to='store.shipingmethod')),
            ],
        ),
        migrations.CreateModel(
            name='ShipingProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiping_method', models.ManyToManyField(related_name='shiping_method', to='store.shipingmethod')),
                ('shiping_range', models.ManyToManyField(related_name='shiping_property', to='store.shipingrange')),
            ],
        ),
    ]
