# Generated by Django 5.1.2 on 2024-11-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_baseproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.producttype'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.productsubcategory'),
        ),
    ]
