# Generated by Django 5.1.2 on 2024-10-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shipingmethod_shipingrange_shipingcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='authenticity',
            field=models.CharField(choices=[('org', 'اورجینال'), ('hc', 'های کپی'), ('c', 'کپی')], default='org', max_length=3),
        ),
    ]
