# Generated by Django 5.1.2 on 2024-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_baseproduct_authenticity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('ap', 'تایید شده'), ('w', 'در انتظار تایید'), ('na', 'تایید نشده')], default='w', max_length=2),
        ),
    ]
