# Generated by Django 5.1.2 on 2024-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_active_status_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reason',
            field=models.TextField(blank=True, help_text='به هنگام  خارج کردن وضعیت محصول از در انتظار تایید این بخش پر شود', null=True),
        ),
    ]
