# Generated by Django 5.1.2 on 2024-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_barcode_alter_product_shenaase_kaala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height_package',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_package',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_package',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_package',
            field=models.IntegerField(),
        ),
    ]
