# Generated by Django 5.1.2 on 2024-10-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='properties',
            field=models.ManyToManyField(related_name='categories', to='store.productproperties'),
        ),
        migrations.CreateModel(
            name='SetProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='store.baseproduct')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productproperties')),
            ],
        ),
    ]
