# Generated by Django 5.1.2 on 2024-11-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_product_brand_baseproduct_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='english_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
