# Generated by Django 5.1.2 on 2024-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productbrand_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='title_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
