# Generated by Django 5.1.2 on 2024-11-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_baseproduct_title_english'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
