# Generated by Django 5.1.2 on 2024-11-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportproduct',
            old_name='products',
            new_name='product',
        ),
    ]
