# Generated by Django 5.1.2 on 2024-10-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_baseproduct_shiping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingproperty',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shiping_property', to='store.store'),
        ),
    ]
