# Generated by Django 5.1.2 on 2024-12-10 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
