# Generated by Django 5.1.2 on 2024-10-15 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_store_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
