# Generated by Django 5.1.2 on 2024-10-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_shipingproperty_shiping_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipingproperty',
            name='shiping_method',
            field=models.ManyToManyField(related_name='shiping_method', to='store.shipingmethod'),
        ),
        migrations.AlterField(
            model_name='shipingproperty',
            name='shiping_range',
            field=models.ManyToManyField(related_name='shiping_property', to='store.shipingrange'),
        ),
        migrations.AlterField(
            model_name='shipingproperty',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiping_property', to='store.store'),
        ),
    ]
