# Generated by Django 5.1.2 on 2024-10-19 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_replycomment_productreplycomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_recipient', models.CharField(max_length=255)),
                ('mobile_recipient', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('email_recipient', models.EmailField(max_length=254)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('pelaak', models.CharField(max_length=15)),
                ('vaahed', models.CharField(max_length=3)),
                ('post_code', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('referrer_code', models.CharField(max_length=255)),
                ('tracking_code', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('ou', 'جاری'), ('od', 'تحویل داده شده'), ('or', 'مرجوع شده'), ('oc', 'لغو شده')], max_length=2)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.city')),
                ('mantaghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.mantaghe')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
