# Generated by Django 5.1.2 on 2024-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_productcolor_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ou', 'جاری'), ('od', 'تحویل داده شده'), ('or', 'مرجوع شده'), ('oc', 'لغو شده')], default='ou', max_length=2),
        ),
    ]
