# Generated by Django 5.1.2 on 2024-10-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_store_store_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='product_code',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
