# Generated by Django 5.1.2 on 2024-10-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_staff_datetime_updated'),
        ('store', '0038_alter_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='panel.staff'),
        ),
    ]
