# Generated by Django 5.1.2 on 2024-10-29 11:09

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(default=store.models.generate_order_tracking_code, max_length=25, unique=True),
        ),
    ]
