# Generated by Django 5.1.2 on 2024-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestotp',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requestotp',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
