# Generated by Django 5.1.2 on 2024-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_requestotp_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestotp',
            name='mobile',
        ),
        migrations.AddField(
            model_name='requestotp',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
