# Generated by Django 5.1.2 on 2024-10-17 18:27

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_requestotp_mobile_requestotp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestotp',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='requestotp',
            name='valid_until',
            field=models.DateTimeField(default=core.models.get_datetime_now, null=True),
        ),
    ]
