# Generated by Django 5.1.2 on 2024-11-01 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=255, verbose_name='پست سازمانی')),
                ('reason_leaving_work', models.TextField()),
                ('duration_activity_based_month', models.IntegerField()),
                ('insurance_period_based_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_subject', models.CharField(choices=[('r', 'ثبت نام'), ('c', 'قرارداد با فیروزجاه'), ('b', 'صورتحساب'), ('a', 'حساب کاربری')], max_length=1)),
                ('type', models.CharField(choices=[('ms', 'ثبت موضوع اصلی'), ('q', 'پرسش')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeForSellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percent', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=12, validators=[django.core.validators.validate_integer])),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPhotographyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_num', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('address', models.TextField()),
                ('store_name', models.CharField(max_length=255)),
                ('request_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SetProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('m', 'مرد'), ('f', 'زن')], max_length=1)),
                ('marital_status', models.CharField(choices=[('s', 'مجرد'), ('m', 'متاهل')], max_length=1)),
                ('code_melly', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('shomare_shnasnaame', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('mobile_num', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('phone_num', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('university_degree', models.CharField(choices=[('di', 'دیپلم'), ('fd', 'فوق دیپلم'), ('l', 'لیسانس'), ('fl', 'فوق لیسانس'), ('d', 'دکترا')], max_length=2)),
                ('field_of_study', models.CharField(max_length=255)),
                ('militari_status', models.CharField(choices=[('m', 'معاف')], max_length=2)),
                ('shomare_shabaa', models.CharField(max_length=26)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('description', models.TextField()),
                ('tasvire_personelly', models.ImageField(null=True, upload_to='staffs/tasvire_personelly/')),
                ('cart_melly', models.ImageField(null=True, upload_to='staffs/cart_melly/')),
                ('shenasnaame_image', models.ImageField(null=True, upload_to='staffs/shenasnaame_image/')),
                ('university_degree_image', models.ImageField(null=True, upload_to='staffs/university_degree_image/')),
                ('adame_sooe_pishine', models.ImageField(null=True, upload_to='staffs/adame_sooe_pishine/')),
                ('cart_payan_khedmat', models.ImageField(null=True, upload_to='staffs/cart_payan_khedmat/')),
                ('level_english', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('computer_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('finance_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('digital_marketing_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('photography_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('areas_of_cooperation_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('minimum_salary_requested', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wa', 'در انتظار تایید'), ('ap', 'تایید شده'), ('su', 'تعلیق'), ('na', 'عدم تایید')], default='wa', max_length=2)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('slider_settings', 'slider settings'), ('contract_settings', 'contract settings'), ('list_of_staffs', 'list of staffs'), ('list_of_users', 'list of users'), ('list_of_products (approved)', 'list of products (approved)'), ('list_of_products (waiting)', 'list of products (waiting)'), ('list_of_all_products', 'list of all products'), ('list_of_products (not_approved)', 'list of products (not approved)'), ('create_new_product', 'create new product'), ('list_of_stores (waiting)', 'list of stores (waiting)'), ('list_of_stores (approved)', 'list of stores (approved)'), ('list_of_stores (not_approved)', 'list of stores (not approved)'), ('support_of_stores', 'support of stores'), ('orders (delivered)', 'orders (delivered)'), ('list_of_customers', 'list of customers'), ('add_category', 'add category'), ('add_item', 'add item'), ('request_photography_service', 'request photography service'), ('backup', 'backup'), ('index_page', 'index page'), ('banner_settings', 'banner settings'), ('registration_of_staff', 'registration of staff'), ('request_staff', 'request staff'), ('contact_us', 'contact us'), ('list_of_all_stores', 'list of all stores'), ('list_of_all_orders', 'list of all orders'), ('list_of_return_orders', 'list of return orders'), ('list_of_current_orders', 'list of current orders'), ('list_of_canceled_orders', 'list of canceled orders'), ('all_categories', 'all categories'), ('add_product_type', 'add product type'), ('pages_settings', 'pages settings'), ('support_customers', 'support customers'), ('support_staffs', 'support staffs'), ('add_sub_category', 'add sub category'), ('transactions', 'transactions'), ('common_questions', 'common questions'), ('web_mail', 'web mail'), ('public_settings', 'public settings'), ('product_box_settings', 'product_box_settings'), ('edit_profile', 'edit profile'), ('fee_for_selling', 'fee for selling')],
            },
        ),
    ]
