# Generated by Django 5.1.2 on 2024-10-19 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        ('store', '0032_productcolor_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('m', 'مرد'), ('f', 'زن')], max_length=1)),
                ('marital_status', models.CharField(choices=[('s', 'مجرد'), ('m', 'متاهل')], max_length=1)),
                ('code_melly', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('shomare_shnasnaame', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('mobile_num', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('phone_num', models.CharField(max_length=11, validators=[django.core.validators.validate_integer])),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('university_degree', models.CharField(choices=[('di', 'دیپلم'), ('fd', 'فوق دیپلم'), ('l', 'لیسانس'), ('fl', 'فوق لیسانس'), ('d', 'دکترا')], max_length=2)),
                ('field_of_study', models.CharField(max_length=255)),
                ('militari_status', models.CharField(choices=[('m', 'معاف')], max_length=2)),
                ('shomare_shabaa', models.CharField(max_length=26)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=10, validators=[django.core.validators.validate_integer])),
                ('tasvire_personelly', models.ImageField(upload_to='staffs/tasvire_personelly/')),
                ('cart_melly', models.ImageField(upload_to='staffs/cart_melly/')),
                ('shenasnaame_image', models.ImageField(upload_to='staffs/shenasnaame_image/')),
                ('university_degree_image', models.ImageField(upload_to='staffs/university_degree_image/')),
                ('adame_sooe_pishine', models.ImageField(upload_to='staffs/adame_sooe_pishine/')),
                ('cart_payan_khedmat', models.ImageField(upload_to='staffs/cart_payan_khedmat/')),
                ('level_english', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('computer_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('finance_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('digital_marketing_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('photography_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('areas_of_cooperation_level', models.CharField(choices=[('k', 'خوب'), ('kk', 'خیلی خوب'), ('a', 'عالی')], max_length=2)),
                ('minimum_salary_requested', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='store.city')),
                ('mantaghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='store.mantaghe')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='store.province')),
            ],
        ),
    ]
