# Generated by Django 5.1.2 on 2024-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_careerrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
