# Generated by Django 5.1.2 on 2024-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_subject', models.CharField(choices=[('r', 'ثبت نام'), ('c', 'قرارداد با فیروزجاه'), ('b', 'صورتحساب'), ('a', 'حساب کاربری')], max_length=1)),
                ('type', models.CharField(choices=[('ms', 'ثبت موضوع اصلی'), ('q', 'پرسش')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
