# Generated by Django 5.1.2 on 2024-10-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_commonquestion'),
        ('store', '0032_productcolor_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeForSellingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percent', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='store.productcategory')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='store.producttype')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_fees', to='panel.staff')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='store.productsubcategory')),
            ],
        ),
    ]
