# Generated by Django 5.1.2 on 2024-10-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_staff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('wa', 'در انتظار تایید'), ('ap', 'تایید شده'), ('su', 'تعلیق'), ('na', 'عدم تایید')], default='wa', max_length=2),
        ),
    ]
