# Generated by Django 5.1.2 on 2024-10-24 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
