# Generated by Django 5.1.2 on 2024-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_staff_reason_alter_staff_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
