# Generated by Django 5.1.2 on 2024-10-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_staff_staff_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_permissions',
        ),
    ]
