# Generated by Django 5.1.2 on 2024-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_remove_staff_staff_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='adame_sooe_pishine',
            field=models.ImageField(null=True, upload_to='staffs/adame_sooe_pishine/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='cart_melly',
            field=models.ImageField(null=True, upload_to='staffs/cart_melly/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='cart_payan_khedmat',
            field=models.ImageField(null=True, upload_to='staffs/cart_payan_khedmat/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shenasnaame_image',
            field=models.ImageField(null=True, upload_to='staffs/shenasnaame_image/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tasvire_personelly',
            field=models.ImageField(null=True, upload_to='staffs/tasvire_personelly/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='university_degree_image',
            field=models.ImageField(null=True, upload_to='staffs/university_degree_image/'),
        ),
    ]
