# Generated by Django 5.1.2 on 2024-10-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_page_datetime_modified_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonquestion',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='common_questions', to='panel.staff'),
            preserve_default=False,
        ),
    ]
