# Generated by Django 5.1.2 on 2024-10-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_commonquestion_staff'),
        ('store', '0039_product_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeforsellingproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_fees', to='store.store'),
        ),
    ]
